### ISSUE TITLE
please help me the error

### ISSUE THREAD

**Issue by ivanzhujunwei** [moell-peng/webim#1]
When I open the URL, it shows "不妙，链接断开了", any suggestions how to solve the issue?
![wx20171202-144044](https://user-images.githubusercontent.com/14146339/33511433-f414d8da-d76e-11e7-9892-7a72d674ff37.png)

**Comment by moell-peng** [comment]
Please check if your port is connectable or if you need to change the config.server address in /public/js/webim.js
