### ISSUE TITLE
安装不了

### ISSUE THREAD

**Issue by cocochent** [moell-peng/webim#2]
[Composer\Downloader\TransportException]
  The "https://files.phpcomposer.com/files/eaglewu/swoole-ide-helper/33db18ad
  87a1f49f4a71a7b76d34602ca8d3be97.zip" file could not be downloaded: SSL ope
  ration failed with code 1. OpenSSL Error messages:
  error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify
  failed
  Failed to enable crypto
  failed to open stream: operation failed

**Comment by moell-peng** [comment]
https://pkg.phpcomposer.com/ 现在不更新了， 你试试其他镜像，你这里不能下载swoole-ide-helper,或者你可以去除这个依赖组件。

**Comment by cocochent** [comment]
好的
